version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    container_name: real_time_poll_api_db
    restart: always
    environment:
      POSTGRES_DB: real_time_poll_api_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_db:
    image: redis:latest
    container_name: pub_sub_db
    restart: always
    ports:
      - '6379:6379'

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: real_time_poll_api
    depends_on:
      - postgres_db
      - redis_db
    ports:
      - '3000:3000'
    env_file: ./.env
    command: npm run start

volumes:
  postgres_data:
